### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by askdong** [dkaip/CSharpSECSTools#1]
there are a lot of compiling error, for example:
"The type or namespace name 'HSMSReader' could not be found (are you missing a using directive or an assembly reference?)	SECSCommUtils	D:\temp\CSharpSECSTools-master\SECSCommUtils\HSMS\HSMSConnection.cs	189	Active"

**Comment by dkaip** [comment]
I have modified the code so that it should now compile (with warnings) until I am able to implement and test the next set of features.  The code in SECSItems and SECSItemTests should compile cleanly and execute properly.
